version: '3.8'

services:
  larabstrait:
    build: .
    container_name: larabstrait-app
    restart: unless-stopped
    ports:
      # On utilise le port 3050 à l'extérieur pour éviter tout conflit sur le NAS
      # (Il faudra juste mettre 3050 dans le proxy inversé plus tard)
      - "3050:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # On utilise un volume nommé, Portainer gérera le dossier tout seul comme un grand
      - larabstrait_data:/app/data

# On déclare le volume nommé ici
volumes:
  larabstrait_data: